# config.yaml
# — значения по-умолчанию: можешь менять в любой момент —

interval:       60      # секунд между сравнениями/снимками
threshold_pct:  0.1     # выводить, если |Δ| ≥ …
max_files:      50      # хранить не более N CSV-файлов
snap_dir:       snapshots
top_to_print:   20      # сколько пар выводить в глобальном режиме
focus:          null    # например "FUNUSDT" — будет работать как --focus
